### ISSUE TITLE
Exception MainActivity.onCreateOptionsMenu(MainActivity.java:528)

### ISSUE THREAD

**Issue by y-polek** [y-polek/TransmissionRemote#47]
Crashlytics#16

Fatal Exception: android.content.res.Resources$NotFoundException: String resource ID #0x7f06009a
       at android.content.res.Resources.getText(Resources.java:303)
       at android.content.res.Resources.getString(Resources.java:389)
       at android.content.Context.getString(Context.java:347)
       at android.widget.SearchView.updateQueryHint(SearchView.java:1070)
       at android.widget.SearchView.setSearchableInfo(SearchView.java:347)
       at net.yupol.transmissionremote.app.MainActivity.onCreateOptionsMenu(MainActivity.java:528)
       at android.app.Activity.onCreatePanelMenu(Activity.java:2579)
       at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:362)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:92)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:331)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:92)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5395)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by y-polek** [comment]
d508ec3ab94893b56b38c5e73311dd5dd30e2f92
